services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}

  worker:
    build:
      context: .
    command: celery -A config worker --loglevel=info
    volumes:
      - static_volume:/app/backend/django_static
    environment:
      - CELERY_BROKER_URL=${CELERY_REDIS_URL}
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  ollama:
    build:
      context: ./ollamaservice
      dockerfile: Dockerfile

    ports:
    - "11434:11434"  # Change to a different external port
    volumes:
      - ollama_data:/ollama

    entrypoint: ["/bin/bash", "/pull-llama.sh"]

volumes:
  postgres_data:
  static_volume:
  media_volume: 
  ollama_data:
    driver: local